install_path = [userpath,'/SNPLIB'];
openblas_root = '/local/usr';
openblas_lib = ['LINKLIBS=$LINKLIBS -L"',openblas_root,'/lib" -lopenblas -lgfortran'];
openblas_include = ['-I"',openblas_root,'/include"'];
cxxoptim = 'CXXOPTIMFLAGS=$CXXOPTIMFLAGS -O3 -std=c++11 -march=native -pipe -fPIC -flto -DUSE_OPENBLAS';
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/UnpackResGeno_.cc','src/snp.cc','src/logistic_utils.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/CalcAdjustedGRM_.cc','src/snp.cc','src/adjusted_grm.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/CalcAdmixedGRM_.cc','src/snp.cc','src/adjusted_grm.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/CalcAdjustedMAF_.cc','src/snp.cc','src/logistic_utils.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/CalcAdjustedAF_.cc','src/snp.cc','src/logistic_utils.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/CalcLogisticGWAS_.cc','src/snp.cc','src/logistic_utils.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/@SNPLIB/CalcSNPGFT_.cc','src/snp.cc','src/logistic_utils.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/GMLM/CalcUniMLM_.cc','src/uni_mlm_utils.cc','src/uni_mlm.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/GMLM/CalcUniMLMGWAS_.cc','src/uni_mlm_utils.cc','src/uni_mlm.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/GMLM/CalcMMLMSigmas_.cc','src/multi_mlm_rml.cc','src/multi_mlm_reml.cc','src/multi_mlm_utils.cc');
mex(cxxoptim,openblas_include,openblas_lib,'matlab/GMLM/CalcRMLMSigmas_.cc','src/multi_mlm_rml.cc','src/multi_mlm_reml.cc','src/multi_mlm_utils.cc');
mex(cxxoptim,'matlab/@SNPLIB/FlipGeno_.cc','src/snp.cc','src/base.cc');
mex(cxxoptim,'matlab/@SNPLIB/Keep_.cc','src/snp.cc','src/base.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcAlleleFrequencies_.cc','src/snp.cc','src/base.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcCallrates_.cc','src/snp.cc','src/base.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcGRMMatrix_.cc','src/snp.cc','src/grm.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcGCTADiagonal_.cc','src/snp.cc','src/grm.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcIBSMatrix_.cc','src/snp.cc','src/ibs.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcIBSConnect_.cc','src/snp.cc','src/ibs.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcUGRMMatrix_.cc','src/snp.cc','src/ugrm.cc');
mex(cxxoptim,'matlab/@SNPLIB/CalcKING_.cc','src/snp.cc','src/king.cc');
mex(cxxoptim,'matlab/@SNPLIB/UnpackPCA_.cc','src/snp.cc','src/grm.cc');
mex(cxxoptim,'matlab/@SNPLIB/UnpackUG_.cc','src/snp.cc','src/ugrm.cc');
mex(cxxoptim,'matlab/@SNPLIB/UnpackGENO_.cc');
mex(cxxoptim,'matlab/misc/pack_.cc');
mex(cxxoptim,'matlab/misc/unpack_.cc');
mex(cxxoptim,'matlab/misc/generate_random_siblings_.cc')
mex(cxxoptim,'matlab/misc/generate_pairwise_siblings_.cc')
mex(cxxoptim,'matlab/misc/generate_admix_.cc');
mex(cxxoptim,'matlab/misc/generate_indivs_.cc');
mex(cxxoptim,'matlab/misc/update_af_.cc');
mkdir(install_path);
copyfile('matlab/@SNPLIB/*.m',[install_path,'/@SNPLIB']);
copyfile('matlab/GMLM/*.m',[install_path,'/GMLM']);
copyfile('matlab/misc/*.m',[install_path,'/misc']);
movefile(['*.',mexext],[install_path,'/mexfiles']);
cd(install_path);
clear all;